/**
 * Master reference list of all 76 official UK cities.
 * This is solely a selection master list for the Super Admin.
 * Cities in this list are NOT automatically supported until activated by Super Admin.
 */
const UK_CITIES = [
  "Bath",
  "Birmingham",
  "Bradford",
  "Brighton and Hove",
  "Bristol",
  "Cambridge",
  "Canterbury",
  "Carlisle",
  "Chelmsford",
  "Chester",
  "Chichester",
  "Colchester",
  "Coventry",
  "Derby",
  "Doncaster",
  "Durham",
  "Ely",
  "Exeter",
  "Gloucester",
  "Hereford",
  "Kingston upon Hull",
  "Lancaster",
  "Leeds",
  "Leicester",
  "Lichfield",
  "Lincoln",
  "Liverpool",
  "London",
  "Manchester",
  "Milton Keynes",
  "Newcastle upon Tyne",
  "Norwich",
  "Nottingham",
  "Oxford",
  "Peterborough",
  "Plymouth",
  "Portsmouth",
  "Preston",
  "Ripon",
  "Salford",
  "Salisbury",
  "Sheffield",
  "Southampton",
  "Southend-on-Sea",
  "St Albans",
  "Stoke-on-Trent",
  "Sunderland",
  "Truro",
  "Wakefield",
  "Wells",
  "Westminster",
  "Winchester",
  "Wolverhampton",
  "Worcester",
  "York",
  "Aberdeen",
  "Dundee",
  "Dunfermline",
  "Edinburgh",
  "Glasgow",
  "Inverness",
  "Perth",
  "Stirling",
  "Bangor",
  "Cardiff",
  "Newport",
  "St Asaph",
  "St Davids",
  "Swansea",
  "Wrexham",
  "Armagh",
  "Belfast",
  "Lisburn",
  "Londonderry",
  "Newry",
  "Bangor (NI)"
];

module.exports = UK_CITIES;
