/**
 * Master reference list of all recognized UK Cities and Counties.
 * Includes:
 * - England (48 Ceremonial Counties + Major Cities)
 * - Scotland (33 Historic Counties + Major Cities)
 * - Wales (8 Preserved Counties + Major Cities)
 * - Northern Ireland (6 Traditional Counties + Major Cities)
 * 
 * This serves as the master selection list for Super Administrators.
 * Locations in this list are NOT automatically supported until activated in the Admin Portal.
 */
const UK_CITIES = [
  "Aberdeen",
  "Aberdeenshire",
  "Angus",
  "Antrim",
  "Argyll",
  "Armagh",
  "Ayrshire",
  "Banffshire",
  "Bangor",
  "Bangor (NI)",
  "Bath",
  "Bedfordshire",
  "Belfast",
  "Berkshire",
  "Berwickshire",
  "Birmingham",
  "Bradford",
  "Brighton and Hove",
  "Bristol",
  "Buckinghamshire",
  "Bute",
  "Caithness",
  "Cambridge",
  "Cambridgeshire",
  "Canterbury",
  "Cardiff",
  "Carlisle",
  "Chelmsford",
  "Cheshire",
  "Chester",
  "Chichester",
  "City of London",
  "Clackmannanshire",
  "Clwyd",
  "Colchester",
  "Cornwall",
  "Coventry",
  "Cumbria",
  "Derby",
  "Derbyshire",
  "Devon",
  "Doncaster",
  "Dorset",
  "Down",
  "Dumfriesshire",
  "Dunbartonshire",
  "Dundee",
  "Dunfermline",
  "Durham",
  "Dyfed",
  "East Lothian",
  "East Riding of Yorkshire",
  "East Sussex",
  "Edinburgh",
  "Ely",
  "Essex",
  "Exeter",
  "Fermanagh",
  "Fife",
  "Glasgow",
  "Gloucester",
  "Gloucestershire",
  "Greater London",
  "Greater Manchester",
  "Gwent",
  "Gwynedd",
  "Hampshire",
  "Hereford",
  "Herefordshire",
  "Hertfordshire",
  "Inverness",
  "Inverness-shire",
  "Isle of Wight",
  "Kent",
  "Kincardineshire",
  "Kingston upon Hull",
  "Kinross-shire",
  "Kirkcudbrightshire",
  "Lanarkshire",
  "Lancashire",
  "Lancaster",
  "Leeds",
  "Leicester",
  "Leicestershire",
  "Lichfield",
  "Lincoln",
  "Lincolnshire",
  "Lisburn",
  "Liverpool",
  "London",
  "Londonderry",
  "Manchester",
  "Merseyside",
  "Mid Glamorgan",
  "Midlothian",
  "Milton Keynes",
  "Moray",
  "Nairnshire",
  "Newcastle upon Tyne",
  "Newport",
  "Newry",
  "Norfolk",
  "North Yorkshire",
  "Northamptonshire",
  "Northumberland",
  "Norwich",
  "Nottingham",
  "Nottinghamshire",
  "Orkney",
  "Oxford",
  "Oxfordshire",
  "Peeblesshire",
  "Perth",
  "Perthshire",
  "Peterborough",
  "Plymouth",
  "Portsmouth",
  "Powys",
  "Preston",
  "Renfrewshire",
  "Ripon",
  "Ross and Cromarty",
  "Roxburghshire",
  "Rutland",
  "Salford",
  "Salisbury",
  "Selkirkshire",
  "Sheffield",
  "Shetland",
  "Shropshire",
  "Somerset",
  "South Glamorgan",
  "South Yorkshire",
  "Southampton",
  "Southend-on-Sea",
  "St Albans",
  "St Asaph",
  "St Davids",
  "Staffordshire",
  "Stirling",
  "Stirlingshire",
  "Stoke-on-Trent",
  "Suffolk",
  "Sunderland",
  "Surrey",
  "Sutherland",
  "Swansea",
  "Truro",
  "Tyne and Wear",
  "Tyrone",
  "Wakefield",
  "Warwickshire",
  "Wells",
  "West Glamorgan",
  "West Lothian",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Westminster",
  "Wigtownshire",
  "Wiltshire",
  "Winchester",
  "Wolverhampton",
  "Worcester",
  "Worcestershire",
  "Wrexham",
  "York"
];

module.exports = UK_CITIES;
