/**
 * Master reference list of all recognized UK Cities, Towns, and Counties.
 * Includes:
 * - England (Ceremonial Counties + Major Cities & Postal Towns)
 * - Scotland (Counties + Major Cities & Postal Towns)
 * - Wales (Counties + Major Cities & Postal Towns)
 * - Northern Ireland (Counties + Major Cities & Postal Towns)
 * 
 * This serves as the master selection list for Super Administrators.
 */
const UK_CITIES = [
  "Aberdeen",
  "Aberdeenshire",
  "Angus",
  "Antrim",
  "Argyll",
  "Armagh",
  "Ayrshire",
  "Banffshire",
  "Bangor",
  "Bangor (NI)",
  "Bath",
  "Bedfordshire",
  "Belfast",
  "Berkshire",
  "Berwickshire",
  "Birmingham",
  "Blackburn",
  "Blackpool",
  "Bolton",
  "Bournemouth",
  "Bradford",
  "Brighton",
  "Brighton and Hove",
  "Bristol",
  "Buckinghamshire",
  "Bute",
  "Caithness",
  "Cambridge",
  "Cambridgeshire",
  "Canterbury",
  "Cardiff",
  "Carlisle",
  "Chelmsford",
  "Cheshire",
  "Chester",
  "Chichester",
  "City of London",
  "Clackmannanshire",
  "Cleveland",
  "Clwyd",
  "Colchester",
  "Cornwall",
  "Coventry",
  "Crewe",
  "Cumbria",
  "Darlington",
  "Derby",
  "Derbyshire",
  "Devon",
  "Doncaster",
  "Dorchester",
  "Dorset",
  "Down",
  "Dudley",
  "Dumfries",
  "Dumfriesshire",
  "Dunbartonshire",
  "Dundee",
  "Dunfermline",
  "Durham",
  "Dyfed",
  "East Lothian",
  "East Riding of Yorkshire",
  "East Sussex",
  "Edinburgh",
  "Ely",
  "Essex",
  "Exeter",
  "Falkirk",
  "Fermanagh",
  "Fife",
  "Galashiels",
  "Glasgow",
  "Gloucester",
  "Gloucestershire",
  "Greater London",
  "Greater Manchester",
  "Guildford",
  "Gwent",
  "Gwynedd",
  "Halifax",
  "Hampshire",
  "Harrogate",
  "Hemel Hempstead",
  "Hereford",
  "Herefordshire",
  "Hertfordshire",
  "Huddersfield",
  "Inverness",
  "Inverness-shire",
  "Ipswich",
  "Isle of Wight",
  "Kent",
  "Kilmarnock",
  "Kincardineshire",
  "Kingston upon Hull",
  "Kinross-shire",
  "Kirkcaldy",
  "Kirkcudbrightshire",
  "Kirkwall",
  "Lanarkshire",
  "Lancashire",
  "Lancaster",
  "Leeds",
  "Leicester",
  "Leicestershire",
  "Lichfield",
  "Lincoln",
  "Lincolnshire",
  "Lisburn",
  "Liverpool",
  "Llandrindod Wells",
  "Llandudno",
  "London",
  "Londonderry",
  "Luton",
  "Manchester",
  "Medway",
  "Merseyside",
  "Mid Glamorgan",
  "Midlothian",
  "Milton Keynes",
  "Moray",
  "Motherwell",
  "Nairnshire",
  "Newcastle upon Tyne",
  "Newport",
  "Newry",
  "Norfolk",
  "North Yorkshire",
  "Northampton",
  "Northamptonshire",
  "Northumberland",
  "Norwich",
  "Nottingham",
  "Nottinghamshire",
  "Oldham",
  "Orkney",
  "Outer Hebrides",
  "Oxford",
  "Oxfordshire",
  "Paisley",
  "Peeblesshire",
  "Perth",
  "Perthshire",
  "Peterborough",
  "Plymouth",
  "Portsmouth",
  "Powys",
  "Preston",
  "Reading",
  "Redhill",
  "Renfrewshire",
  "Ripon",
  "Ross and Cromarty",
  "Roxburghshire",
  "Rutland",
  "Salford",
  "Salisbury",
  "Selkirkshire",
  "Sheffield",
  "Shetland",
  "Shrewsbury",
  "Shropshire",
  "Slough",
  "Somerset",
  "South Glamorgan",
  "South Yorkshire",
  "Southampton",
  "Southend-on-Sea",
  "St Albans",
  "St Asaph",
  "St Davids",
  "Staffordshire",
  "Stevenage",
  "Stirling",
  "Stirlingshire",
  "Stockport",
  "Stoke-on-Trent",
  "Suffolk",
  "Sunderland",
  "Surrey",
  "Sutherland",
  "Swansea",
  "Swindon",
  "Taunton",
  "Telford",
  "Tonbridge",
  "Torquay",
  "Truro",
  "Tyne and Wear",
  "Tyrone",
  "Wakefield",
  "Walsall",
  "Warrington",
  "Warwickshire",
  "Wells",
  "West Glamorgan",
  "West Lothian",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Westminster",
  "Wigan",
  "Wigtownshire",
  "Wiltshire",
  "Winchester",
  "Wolverhampton",
  "Worcester",
  "Worcestershire",
  "Wrexham",
  "York"
];

module.exports = UK_CITIES;
